name: Deploy on Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH and Deploy with Retry
    run: |
      MAX_RETRIES=3
      RETRIES=0
      while [ $RETRIES -lt $MAX_RETRIES ]; do
        ssh -o StrictHostKeyChecking=no root@106.15.139.48 << EOF
          cd server
          git stash
          git stash drop
          if git pull; then
            chmod +x ./deploy.sh
            ./deploy.sh restart
            exit 0  # Exit SSH session if deployment is successful
          else
            echo "Failed to pull changes. Retrying..."
            RETRIES=$((RETRIES+1))
            sleep 10  # Adjust sleep duration as needed
          fi
        EOF
      done
      if [ $RETRIES -eq $MAX_RETRIES ]; then
        echo "Max retries reached. Deployment failed."
        exit 1  # Exit with a non-zero status code to indicate failure
      else
        echo "Deployment successful after $RETRIES retries."
      fi
