name: Deploy on Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH and Deploy with Retry
      run: |
        ssh -o StrictHostKeyChecking=no root@106.15.139.48 << EOF
          cd server
          git stash
          git stash drop
          git pull
          chmod +x ./deploy.sh
          ./deploy.sh restart
        EOF
